# CSE 252B: Computer Vision II, Winter 2022 – Assignment 2

### Instructor: Ben Ochoa

### Due: Wednesday, February 2, 2022, 11:59 PM

## Instructions
* Review the academic integrity and collaboration policies on the course website.
* This assignment must be completed individually.
* This assignment contains both math and programming problems.
* All solutions must be written in this notebook
* Math must be done in Markdown/LaTeX.
* You must show your work and describe your solution.
* Programming aspects of this assignment must be completed using Python in this notebook.
* Your code should be well written with sufficient comments to understand, but there is no need to write extra markdown to describe your solution if it is not explictly asked for.
* This notebook contains skeleton code, which should not be modified (This is important for standardization to facilate efficient grading).
* You may use python packages for basic linear algebra, but you may not use packages that directly solve the problem. If you are uncertain about using a specific package, then please ask the instructional staff whether or not it is allowable.
* You must submit this notebook exported as a pdf. You must also submit this notebook as an .ipynb file.
* Your code and results should remain inline in the pdf (Do not move your code to an appendix).
* You must submit both files (.pdf and .ipynb) on Gradescope. You must mark each problem on Gradescope in the pdf.
* It is highly recommended that you begin working on this assignment early.

## Problem 1 (Math): Line-plane intersection (5 points)
  The line in 3D defined by the join of the points $\boldsymbol{X}_1 = (X_1,
  Y_1, Z_1, T_1)^\top$ and $\boldsymbol{X}_2 = (X_2, Y_2, Z_2, T_2)^\top$
  can be represented as a Plucker matrix $\boldsymbol{L} = \boldsymbol{X}_1
  \boldsymbol{X}_2^\top - \boldsymbol{X}_2 \boldsymbol{X}_1^\top$ or pencil of points
  $\boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 - \lambda) \boldsymbol{X}_2$
  (i.e., $\boldsymbol{X}$ is a function of $\lambda$).  The line intersects
  the plane $\boldsymbol{\pi} = (a, b, c, d)^\top$ at the point
  $\boldsymbol{X}_{\boldsymbol{L}} = \boldsymbol{L} \boldsymbol{\pi}$ or
  $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$, where $\lambda_{\boldsymbol{\pi}}$ is
  determined such that $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})^\top \boldsymbol{\pi} =
  0$ (i.e., $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$ is the point on
  $\boldsymbol{\pi}$).  Show that $\boldsymbol{X}_{\boldsymbol{L}}$ is equal to
  $\boldsymbol{X}(\lambda_{\boldsymbol{\pi}})$ up to scale.

We have the following two line representations <br>
Plucker Matrix: $L = X_1X_2^T - X_2X_1^T$ <br>
Pencil of Points representation: $X(\lambda) = \lambda X_1 + (1 - \lambda)X_2$ <br>

For a given plane $\pi = (a, b, c, d)^T$, it is given that a line $L$ or $X(\lambda)$ intersects it at a point
$X_L$ or $X(\lambda_\pi)$ such that $X(\lambda_\pi)^T \pi = 0$. Using the latter equation to solve for $\lambda_\pi$ <br>

$(\lambda X_1 + (1 - \lambda)X_2)^T \pi$ = 0 <br>
$\lambda X_1^T \pi + X_2^T \pi - \lambda X_2^T \pi$ = 0 <br>
$\lambda(X_1^T \pi - X_2^T \pi) = - X_2^T \pi$ <br>
$\lambda = \frac{- X_2^T \pi}{X_1^T \pi - X_2^T \pi}$ <br>

Substituting $\lambda$ back in the pencil of points representation, we get <br>

$X(\lambda_\pi) = \frac{(- X_2^T \pi)X_1}{X_1^T \pi - X_2^T \pi} + \frac{(X_1^T \pi)X_2}{X_1^T \pi - X_2^T \pi}$ <br>
$X(\lambda_\pi) = c(X_1X_2^T \pi - X_2X_1^T \pi)$, where $c = \frac{-1}{X_1^T \pi - X_2^T \pi}$ ....(1)<br>

Substituting $L$ in $X_L = L\pi$, we get

$X_L = (X_1X_2^T - X_2X_1^T)\pi$ <br>
$X_L = X_1X_2^T \pi - X_2X_1^T \pi$ .... (2) <br>

From (1) and (2), we get

$X(\lambda_\pi) = cX_L$

Therefore, $X(\lambda_\pi)$ equals $X_L$ up to scale.

## Problem 2 (Math): Line-quadric intersection (5 points)
  In general, a line in 3D intersects a quadric $\boldsymbol{Q}$ at zero, one
  (if the line is tangent to the quadric), or two points.  If the
  pencil of points $\boldsymbol{X}(\lambda) = \lambda \boldsymbol{X}_1 + (1 -
  \lambda) \boldsymbol{X}_2$ represents a line in 3D, the (up to two) real
  roots of the quadratic polynomial $c_2 \lambda_{\boldsymbol{Q}}^2 + c_1
  \lambda_{\boldsymbol{Q}} + c_0 = 0$ are used to solve for the intersection
  point(s) $\boldsymbol{X}(\lambda_{\boldsymbol{Q}})$.  Show that $c_2 =
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_1 - 2 \boldsymbol{X}_1^\top \boldsymbol{Q}
  \boldsymbol{X}_2 + \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$, $c_1 = 2 (
  \boldsymbol{X}_1^\top \boldsymbol{Q} \boldsymbol{X}_2 - \boldsymbol{X}_2^\top \boldsymbol{Q}
  \boldsymbol{X}_2 )$, and $c_0 = \boldsymbol{X}_2^\top \boldsymbol{Q} \boldsymbol{X}_2$.

Given, a line represented by the pencil of points representation $X(\lambda) = \lambda X_1 + (1 - \lambda)X_2$ and a Quadric $Q$, the intersection points of the line and the quadric are the (upto to two) real roots of the following equation: <br>

$X(\lambda_Q)^T Q X(\lambda_Q) = 0$  <br>
$(\lambda_Q X_1 + (1 - \lambda_Q)X_2)^T Q (\lambda_Q X_1 + (1 - \lambda_Q)X_2) = 0$ <br>

Expanding the above equation, we get <br>

$X_1^TQX_1 \lambda_Q^2 - X_1^TQX_2\lambda_Q^2 - X_1^TQX_2\lambda_Q^2 + X_2^TQX_2\lambda_Q^2 + X_1^TQX_2 \lambda_Q + X_1^TQX_2 \lambda_Q - X_2^TQX_2\lambda_Q - X_2^TQX_2\lambda_Q + X_2^TQX_2 = 0$ <br>
$(X_1^TQX_1 - 2X_1^TQX_2 + X_2^TQX_2)\lambda_Q^2 + (2(X_1^TQX_2 - X_2^TQX_2))\lambda_Q + X_2^TQX_2 = 0$ <br>

This can be rewritten as

$c_2\lambda_Q^2 + c_1\lambda_Q + c_0 = 0$, where <br>

$c_2 = X_1^TQX_1 - 2X_1^TQX_2 + X_2^TQX_2$ <br>
$c_1 = 2(X_1^TQX_2 - X_2^TQX_2)$ <br>
$c_0 = X_2^TQX_2$ <br>

Hence proved.


## Problem 3 (Programming):  Linear Estimation of the Camera Projection Matrix (15 points)
  Download input data from the course website.  The file
  hw2_points3D.txt contains the coordinates of 50 scene points
  in 3D (each line of the file gives the $\tilde{X}_i$, $\tilde{Y}_i$,
  and $\tilde{Z}_i$ inhomogeneous coordinates of a point).  The file
  hw2_points2D.txt contains the coordinates of the 50
  corresponding image points in 2D (each line of the file gives the
  $\tilde{x}_i$ and $\tilde{y}_i$ inhomogeneous coordinates of a
  point).  The scene points have been randomly generated and projected
  to image points under a camera projection matrix (i.e., $\boldsymbol{x}_i
  = \boldsymbol{P} \boldsymbol{X}_i$), then noise has been added to the image point
  coordinates.

  Estimate the camera projection matrix $\boldsymbol{P}_\text{DLT}$ using the
  direct linear transformation (DLT) algorithm (with data
  normalization).  You must express $\boldsymbol{x}_i = \boldsymbol{P} \boldsymbol{X}_i$
  as $[\boldsymbol{x}_i]^\perp \boldsymbol{P} \boldsymbol{X}_i = \boldsymbol{0}$ (not
  $\boldsymbol{x}_i \times \boldsymbol{P} \boldsymbol{X}_i = \boldsymbol{0}$), where
  $[\boldsymbol{x}_i]^\perp \boldsymbol{x}_i = \boldsymbol{0}$, when forming the
  solution. Return
  $\boldsymbol{P}_\text{DLT}$, scaled such that
  $||\boldsymbol{P}_\text{DLT}||_\text{Fro} = 1$
  
  The following helper functions may be useful in your DLT function implementation.
  You are welcome to add any additional helper functions.

In [1]:
import numpy as np
import time

def Homogenize(x):
    # converts points from inhomogeneous to homogeneous coordinates
    return np.vstack((x,np.ones((1,x.shape[1]))))


def Dehomogenize(x):
    # converts points from homogeneous to inhomogeneous coordinates
    return x[:-1]/x[-1]


def Normalize(pts):
    # data normalization of n dimensional pts
    #
    # Input:
    #    pts - is in inhomogeneous coordinates
    # Outputs:
    #    pts - data normalized points
    #    T - corresponding transformation matrix
    
    """your code here"""
    num_axes = pts.shape[0]
    var = np.var(pts, axis=1)
    mean = np.mean(pts, axis=1)
    var_sum = np.sum(var)
    if(num_axes == 2):
        s = np.sqrt(2 / var_sum)
    elif(num_axes == 3):
        s = np.sqrt(3 / var_sum)
        
    T = np.eye(pts.shape[0]+1)
    
    diagonal = np.eye(pts.shape[0]) * s
    T[:num_axes, :num_axes] = diagonal
    
    T[:num_axes, -1] = -mean * s
    points_homogenous = Homogenize(pts)
    pts = np.matmul(T, points_homogenous)
    return pts, T

def ComputeCost(P, x, X):
    # Inputs:
    #    P - the camera projection matrix
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    # Output:
    #    cost - Total reprojection error
    
    """your code here"""
    X = Homogenize(X)
    x_hat = np.matmul(P, X)
    x_hat = Dehomogenize(x_hat)
    epsilon = np.sum(np.power((x - x_hat), 2), axis = 0)
    cost = np.sum(epsilon)
    return cost


In [2]:
def DLT(x, X, normalize=True):
    # Inputs:
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #    normalize - if True, apply data normalization to x and X
    #
    # Output:
    #    P - the (3x4) DLT estimate of the camera projection matrix
    P = np.eye(3,4)+np.random.randn(3,4)/10
        
    # data normalization
    if normalize:
        x, T = Normalize(x)
        X, U = Normalize(X)
    else:
        x = Homogenize(x)
        X = Homogenize(X)
    
    """your code here"""
    x_norm = np.linalg.norm(x, axis = 0)
    signMatrix = np.sign(x[0, :])
    e1 = np.array([1,0,0]).reshape((3,1))
    v = x + np.multiply(np.multiply(signMatrix, x_norm), e1)
    A = np.empty((2 * x.shape[1], x.shape[0] * X.shape[0]))
    I = np.eye(x.shape[0])
    
    for i in range(x.shape[1]):
        vi = v[:, i].reshape((3, 1))
        viT = vi.T
        Hv = I - (2 * np.dot(vi, viT) / np.dot(viT, vi)) # Household matrix
        x_LN = Hv[1:,:] # left nullspace
        A[2*i : 2*i + 2, :] = np.kron(x_LN, X[:, i].T)
    
    _ , _, V = np.linalg.svd(A)
    P = V[-1, :]
    P = np.reshape(P, (3,4))
    # data denormalize
    if normalize:
        P = np.linalg.inv(T) @ P @ U
        
    P = P / np.linalg.norm(P)   
    return P

def displayResults(P, x, X, title):
    print(title+' =')
    print (P/np.linalg.norm(P)*np.sign(P[-1,-1]))

# load the data
x=np.loadtxt('hw2_points2D.txt').T
X=np.loadtxt('hw2_points3D.txt').T

assert x.shape[1] == X.shape[1]
n = x.shape[1]

# compute the linear estimate without data normalization
print ('Running DLT without data normalization')
time_start=time.time()
P_DLT = DLT(x, X, normalize=False)
cost = ComputeCost(P_DLT, x, X)
time_total=time.time()-time_start
# display the results
print('took %f secs'%time_total)
print('Cost=%.9f'%cost)


# compute the linear estimate with data normalization
print ('Running DLT with data normalization')
time_start=time.time()
P_DLT = DLT(x, X, normalize=True)
cost = ComputeCost(P_DLT, x, X)
time_total=time.time()-time_start
# display the results
print('took %f secs'%time_total)
print('Cost=%.9f'%cost)

print("\n==Correct outputs==")
print("Cost=%.9f without data normalization"%97.053718991)
print("Cost=%.9f with data normalization"%84.104680130)

Running DLT without data normalization
took 0.004356 secs
Cost=97.053718991
Running DLT with data normalization
took 0.004908 secs
Cost=84.104680130

==Correct outputs==
Cost=97.053718991 without data normalization
Cost=84.104680130 with data normalization


In [3]:
# Report your P_DLT value here!
displayResults(P_DLT, x, X, 'P_DLT')

P_DLT =
[[ 6.04350846e-03 -4.84282446e-03  8.82395315e-03  8.40441373e-01]
 [ 9.09666810e-03 -2.30374203e-03 -6.18060233e-03  5.41657305e-01]
 [ 5.00625470e-06  4.47558354e-06  2.55223773e-06  1.25160752e-03]]


## Problem 4 (Programming):  Nonlinear Estimation of the Camera Projection Matrix (30 points)
  Use $\boldsymbol{P}_\text{DLT}$ as an initial estimate to an iterative
  estimation method, specifically the Levenberg-Marquardt algorithm,
  to determine the Maximum Likelihood estimate of the camera
  projection matrix that minimizes the projection error.  You must
  parameterize the camera projection matrix as a parameterization of
  the homogeneous vector $\boldsymbol{p} = vec{(\boldsymbol{P}^\top)}$.  It is
  highly recommended to implement a parameterization of homogeneous
  vector method where the homogeneous vector is of arbitrary length,
  as this will be used in following assignments.
  
  Report the initial cost (i.e. cost at iteration 0) and the cost at the end
  of each successive iteration. Show the numerical values for the final 
  estimate of the camera projection matrix $\boldsymbol{P}_\text{LM}$, scaled
  such that $||\boldsymbol{P}_\text{LM}||_\text{Fro} = 1$.
  
  The following helper functions may be useful in your LM function implementation.
  You are welcome <i>and encouraged</i> to add any additional helper functions.
  
  Hint: LM has its biggest cost reduction after the 1st iteration. You'll know if you 
  are implementing LM correctly if you experience this.

In [4]:
# Note that np.sinc is different than defined in class
def Sinc(x):
    # Returns a scalar valued sinc value
    """your code here"""
    if(x == 0):
        return 1
    return np.sin(x) / x

def dSinc(x):
    if(x == 0):
        return 0
    else:
        val = (np.cos(x) / x) - (np.sin(x) / np.power(x, 2))
        return val
    
def Jacobian(P,p,X):
    # compute the jacobian matrix
    #
    # Input:
    #    P - 3x4 projection matrix
    #    p - 11x1 homogeneous parameterization of P
    #    X - 3n 3D scene points
    # Output:
    #    J - 2nx11 jacobian matrix
    J = np.zeros((2*X.shape[1],11))
    
    """your code here"""
    norm_p = np.linalg.norm(p)
    row = p.shape[0]
    a = np.cos(norm_p / 2) # 1x1
    b = 0.5 * Sinc(norm_p / 2) * p # 11x1
    if(norm_p == 0):
        da_dp = np.zeros((1, row))
        db_dp = 0.5 * np.eye(row)
    else:
        da_dp = -0.5 * b.T # 1x11
        db_dp = (0.5 * Sinc(norm_p/2) * np.eye(row)) + \
                (0.25/norm_p * dSinc(0.5 * norm_p) * np.dot(p, p.T)) # 11x11
        
    dP_dp = np.vstack((da_dp, db_dp)) # 12 x 11
    
    p3_T = P[-1, :].reshape((1,4)) # 1x4
    A = np.zeros((2 * X.shape[1], 3 * X.shape[0])) # 2n x 12. X is 4x1
    for i, points in enumerate(X.T):
        X_T =  X[:, i].reshape((4,1))
        wi = np.matmul(p3_T, X_T)# 1x1
        xi = np.matmul(P, X[:,i].reshape(4,1)) # 3x1
        xi_dehomog = Dehomogenize(xi) # 2x1
        zero_vec = np.zeros((1,4)) # 1x4
        X_T = X[:, i].reshape((1,4)) # 1x4
        xX = -xi_dehomog[0,0]* X_T # 1x4
        yX = -xi_dehomog[1,0]* X_T # 1x4
        block_matrix = np.block([[X_T, zero_vec, xX],
                                [zero_vec, X_T, yX]])
        A[2*i : 2*i + 2, :] = (1/wi) * block_matrix
    J = np.matmul(A, dP_dp)
    return J


def Parameterize(P):
    # wrapper function to interface with LM
    # takes all optimization variables and parameterizes all of them
    # in this case it is just P, but in future assignments it will
    # be more useful
    return ParameterizeHomog(P.reshape(-1,1))


def Deparameterize(p):
    # Deparameterize all optimization variables
    return DeParameterizeHomog(p).reshape(3,4)


def ParameterizeHomog(V):
    # Given a homogeneous vector V return its minimal parameterization
    """your code here"""
    frobNorm = np.linalg.norm(V)
    V = V / frobNorm # convert to unit vector
    
    a = V[0, 0]
    b = V[1:,0]
    v = (2 / Sinc(np.arccos(a))) * b
    Vlen = V.shape[0]
    
    norm_v = np.linalg.norm(v)
    if(norm_v == 2 * np.pi):
        v = np.zeros(Vlen-1)
        v[0,0] = -1
    elif(norm_v > np.pi):
        v = 1 - (2*np.pi / norm_v) * np.ceil((norm_v - np.pi) / (2*np.pi)) * v
    v = v.reshape((Vlen-1,1))
    return v


def DeParameterizeHomog(v):
    # Given a parameterized homogeneous vector return its deparameterization
    """your code here"""
    norm = np.linalg.norm(v)
    a = np.cos(norm / 2)
    b = Sinc(norm / 2) / 2 * v
    
    a = np.array([a])
    v_bar = np.vstack((a, b))
    v_bar = v_bar / np.linalg.norm(v_bar)
    return v_bar

def Normalize_withCov(pts, covarx):
    # data normalization of n dimensional pts
    #
    # Input:
    #    pts - is in inhomogeneous coordinates
    #    covarx - covariance matrix associated with x. Has size 2n x 2n, where n is number of points.
    # Outputs:
    #    pts - data normalized points
    #    T - corresponding transformation matrix
    #    covarx - normalized covariance matrix
    
    """your code here"""
    T = np.eye(pts.shape[0]+1)
    pts, T = Normalize(pts)
    s = T[0,0]
    a = s * np.eye(2)
    for i in range(pts.shape[1]):
        covarx[2*i: 2*i+2, 2*i: 2*i+2] = np.matmul(a, np.matmul(covarx[2*i: 2*i+2, 2*i: 2*i+2], a.T))
    return pts, T, covarx

def ComputeCost_withCov(P, x, X, covarx):
    # Inputs:
    #    P - the camera projection matrix
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #    covarx - covariance matrix associated with x. Has size 2n x 2n, where n is number of points.
    # Output:
    #    cost - Total reprojection error
    
    """your code here"""
    epsilon = (Dehomogenize(x) - Dehomogenize(np.dot(P, X))).reshape((2*X.shape[1], 1), order='F')
    cost = np.sum(epsilon.T @ np.linalg.inv(covarx) @ epsilon)
    return cost


In [5]:
def LM(P, x, X, max_iters, lam):
    # Input:
    #    P - initial estimate of P
    #    x - 2D inhomogeneous image points
    #    X - 3D inhomogeneous scene points
    #    max_iters - maximum number of iterations
    #    lam - lambda parameter
    # Output:
    #    P - Final P (3x4) obtained after convergence
    
    # data normalization
    covarx = np.eye(2*X.shape[1])
    x, T, covarx = Normalize_withCov(x, covarx)
    X, U = Normalize(X)
    
    
    """your code here"""
    lam = 0.001
    
    P = T @ P @ np.linalg.inv(U)
    P = P / np.linalg.norm(P)
    cost_prev = ComputeCost_withCov(P, x, X, covarx)
    
    # you may modify this so long as the cost is computed
    # at each iteration
    i = 0
    while i < max_iters:
        # outer loop
        P = P / np.linalg.norm(P)*np.sign(P[-1,-1])
        p = Parameterize(P)
        J = Jacobian(P, p, X)
        eps = (Dehomogenize(x) - Dehomogenize(np.dot(P, X))).reshape((2*X.shape[1], 1), order='F')
        A = J.T @ np.linalg.inv(covarx) @ J
        b = J.T @ np.linalg.inv(covarx) @ eps
        
        # inner loop
        A_augmented = A + lam * np.eye(J.shape[1])
        delta = np.linalg.inv(A_augmented) @ b
        p_0 = p + delta
        P_0 = Deparameterize(p_0)
        eps_0 = (Dehomogenize(x) - Dehomogenize(np.dot(P_0, X))).reshape((2*X.shape[1], 1), order='F')
        cost_0 = ComputeCost_withCov(P_0, x, X, covarx)
        
        if(1 - cost_0/cost_prev < 1e-12):
            break
        
        if(cost_0 < cost_prev):
            P = P_0
            eps = eps_0
            lam = 0.1 * lam
            cost_prev = cost_0
            print ('iter %03d Cost %.9f'%(i+1, cost_0))
            i = i + 1
        else:
            lam = 10.0 * lam
    # data denormalization
    P = np.linalg.inv(T) @ P @ U
    return P



# LM hyperparameters
lam = .001
max_iters = 100

# Run LM initialized by DLT estimate with data normalization
print ('Running LM with data normalization')
print ('iter %03d Cost %.9f'%(0, cost))
time_start=time.time()
P_LM = LM(P_DLT, x, X, max_iters, lam)
time_total=time.time()-time_start
print('took %f secs'%time_total)

print("\n==Correct outputs==")
print("Begins at %.9f; ends at %.9f"%(84.104680130, 82.790238005))

Running LM with data normalization
iter 000 Cost 84.104680130
iter 001 Cost 82.791336044
iter 002 Cost 82.790238006
iter 003 Cost 82.790238005
took 0.023962 secs

==Correct outputs==
Begins at 84.104680130; ends at 82.790238005


In [6]:
# Report your P_LM final value here!
displayResults(P_LM, x, X, 'P_LM')

P_LM =
[[ 6.09434291e-03 -4.72647758e-03  8.79023503e-03  8.43642842e-01]
 [ 9.02017241e-03 -2.29290824e-03 -6.13330068e-03  5.36660248e-01]
 [ 4.99088611e-06  4.45205073e-06  2.53705045e-06  1.24348254e-03]]
